
[Pixels]
tdac = 0

# Select core column ranges to be disabled (all core columns are enabled by default).
# eg.: [[0, 16], [32, 64]]
[CoreColumns]
disable = []
disableInjections = []

# Set chip registers.
[Registers]
DAC_PREAMP_L_LIN = 300
DAC_PREAMP_R_LIN = 300
DAC_PREAMP_TL_LIN = 300
DAC_PREAMP_TR_LIN = 300
DAC_PREAMP_T_LIN = 300
DAC_PREAMP_M_LIN = 300
DAC_FC_LIN = 20
DAC_KRUM_CURR_LIN = 70
DAC_REF_KRUM_LIN = 360
DAC_COMP_LIN = 110
DAC_COMP_TA_LIN = 110
DAC_GDAC_L_LIN = 500
DAC_GDAC_R_LIN = 500
DAC_GDAC_M_LIN = 500
DAC_LDAC_LIN = 110
LEACKAGE_FEEDBACK = 0
AnalogInjectionMode = 0
VCAL_HIGH = 1800
VCAL_MED = 300
TRIM_VREFD = 1
TRIM_VREFA = 5

